# Generated by Django 5.1.7 on 2025-03-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_class_course_teacher_classcourse_student_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classcourse',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='teacherclass',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='classcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursetime',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursetime',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='status',
            name='course_time',
        ),
        migrations.RemoveField(
            model_name='status',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacherclass',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='ClassCourse',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseTime',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
        migrations.DeleteModel(
            name='TeacherClass',
        ),
    ]
