# Generated by Django 5.1.7 on 2025-03-20 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_management', '0002_initial'),
        ('user_management', '0003_remove_classcourse_class_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentrate', models.IntegerField()),
                ('sleepy', models.IntegerField()),
                ('low_head', models.IntegerField()),
                ('half', models.CharField(max_length=45)),
                ('puzzle', models.IntegerField()),
                ('if_come', models.BooleanField(default=False)),
                ('course_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='course_management.coursetime')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='user_management.student')),
            ],
        ),
    ]
