# Generated by Django 5.1.7 on 2025-03-25 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_management", "0006_remove_courseannouncement_course_and_more"),
        ("status_management", "0001_initial"),
        ("user_management", "0007_alter_student_student_id_alter_teacher_teacher_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name": "课堂状态", "verbose_name_plural": "课堂状态"},
        ),
        migrations.AlterField(
            model_name="status",
            name="concentrate",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="status",
            name="course_time",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="statuses",
                to="course_management.coursetime",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="half",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="status",
            name="low_head",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="status",
            name="puzzle",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="status",
            name="sleepy",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="status",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="statuses",
                to="user_management.student",
            ),
        ),
    ]
