# Generated by Django 5.1.7 on 2025-03-22 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0002_initial'),
        ('user_management', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetime',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_times', to='user_management.teacher'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_courses', to='user_management.student'),
        ),
    ]
