# Generated by Django 5.1.7 on 2025-03-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0003_alter_coursetime_teacher_alter_studentcourse_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetime',
            options={'verbose_name': '课程时间', 'verbose_name_plural': '课程时间'},
        ),
        migrations.AlterField(
            model_name='coursetime',
            name='begin_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='coursetime',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
    ]
