# Generated by Django 5.1.7 on 2025-03-22 10:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0004_alter_coursetime_options_alter_coursetime_begin_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classcourse',
            options={'verbose_name': '班级课程', 'verbose_name_plural': '班级课程'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='studentcourse',
            options={'verbose_name': '学生选课', 'verbose_name_plural': '学生选课'},
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('type', models.CharField(choices=[('homework', '作业'), ('exam', '考试')], default='homework', max_length=10, verbose_name='类型')),
                ('description', models.TextField(verbose_name='描述')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('full_score', models.IntegerField(default=100, verbose_name='总分')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='course_management.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '作业/考试',
                'verbose_name_plural': '作业/考试',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CourseAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('type', models.CharField(choices=[('info', '普通'), ('warning', '重要'), ('danger', '紧急')], default='info', max_length=10, verbose_name='类型')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='course_management.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '课程公告',
                'verbose_name_plural': '课程公告',
                'ordering': ['-created_at'],
            },
        ),
    ]
