# Generated by Django 5.1.7 on 2025-03-28 19:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_management", "0006_remove_courseannouncement_course_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseresource",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="course_management.course",
                verbose_name="所属课程",
            ),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="file",
            field=models.FileField(
                upload_to="course_resources/", verbose_name="资源文件"
            ),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="name",
            field=models.CharField(max_length=255, verbose_name="资源名称"),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="size",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=20,
                verbose_name="文件大小",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="type",
            field=models.CharField(max_length=50, verbose_name="资源类型"),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="uploader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_resources",
                to=settings.AUTH_USER_MODEL,
                verbose_name="上传者",
            ),
        ),
    ]
