# Generated by Django 5.1.7 on 2025-03-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Face",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("feat", models.BinaryField()),
            ],
            options={
                "db_table": "faces",
            },
        ),
    ]
