# Generated by Django 5.1.7 on 2025-03-29 11:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course_management", "0007_alter_courseresource_course_and_more"),
        ("user_management", "0007_alter_student_student_id_alter_teacher_teacher_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                (
                    "type",
                    models.CharField(
                        choices=[("homework", "作业"), ("exam", "考试")],
                        default="homework",
                        max_length=10,
                        verbose_name="类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="描述")),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("deadline", models.DateTimeField(verbose_name="截止时间")),
                (
                    "full_score",
                    models.PositiveIntegerField(default=100, verbose_name="满分"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="course_management.course",
                        verbose_name="所属课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "作业与考试",
                "verbose_name_plural": "作业与考试",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="CourseAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="公告标题")),
                ("content", models.TextField(verbose_name="公告内容")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("info", "普通"),
                            ("warning", "重要"),
                            ("danger", "紧急"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="公告类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="course_management.course",
                        verbose_name="所属课程",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布者",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程公告",
                "verbose_name_plural": "课程公告",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assignment_submissions/%Y/%m/",
                        verbose_name="提交文件",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="提交内容"),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="得分"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="教师反馈"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="提交时间"
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="advanced_features.assignment",
                        verbose_name="作业",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_submissions",
                        to="user_management.student",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "作业提交",
                "verbose_name_plural": "作业提交",
                "unique_together": {("assignment", "student")},
            },
        ),
        migrations.CreateModel(
            name="CourseGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分组名称")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="course_management.course",
                        verbose_name="所属课程",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="groups",
                        to="user_management.student",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程分组",
                "verbose_name_plural": "课程分组",
                "unique_together": {("name", "course")},
            },
        ),
    ]
