# Generated by Django 5.1.7 on 2025-03-20 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_management', '0001_initial'),
        ('user_management', '0002_class_course_teacher_classcourse_student_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_classes', to='user_management.teacher'),
        ),
    ]
