# Generated by Django 5.1.7 on 2025-03-22 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0002_initial'),
        ('user_management', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': '班级', 'verbose_name_plural': '班级'},
        ),
        migrations.AlterModelOptions(
            name='teacherclass',
            options={'verbose_name': '教师班级关联', 'verbose_name_plural': '教师班级关联'},
        ),
        migrations.AlterField(
            model_name='teacherclass',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_classes', to='user_management.teacher'),
        ),
    ]
